# Generated by Django 5.2.17 on 2026-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('MANAGER', 'Gestionnaire'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=10),
        ),
    ]
